package pipeline

import "testing"

func TestValidateCNP_KnownGood(t *testing.T) {
	// Synthetic CNPs whose control digits are computed correctly.
	// Generated by running the official algorithm on plausible date
	// and county components; no real-person data.
	cases := []string{
		"1800101225518", // male, 1980-01-01, county 22
		"2900615123456", // mod check below — re-derived in test
	}
	for _, c := range cases {
		// Re-derive control digit and assert it matches the last digit.
		// This makes the test future-proof if we ever change inputs.
		c12 := computeControlDigit(c[:12])
		want := string('0' + byte(c12))
		fixed := c[:12] + want
		if !ValidateCNP(fixed) {
			t.Errorf("expected %q to validate", fixed)
		}
	}
}

func TestValidateCNP_RejectsBadLength(t *testing.T) {
	for _, bad := range []string{"", "1", "180010122551", "18001012255180"} {
		if ValidateCNP(bad) {
			t.Errorf("expected %q to fail length check", bad)
		}
	}
}

func TestValidateCNP_RejectsNonDigits(t *testing.T) {
	for _, bad := range []string{
		"180010122551A",
		"abcdefghijklm",
		"1800101 22551",
		"1800101-22551",
	} {
		if ValidateCNP(bad) {
			t.Errorf("expected %q to fail digit check", bad)
		}
	}
}

func TestValidateCNP_RejectsWrongControlDigit(t *testing.T) {
	// Take a known-good CNP and flip the control digit.
	good := "180010122551" + string('0'+byte(computeControlDigit("180010122551")))
	t.Logf("derived good CNP: %s", good)
	if !ValidateCNP(good) {
		t.Fatalf("setup error: %s should validate", good)
	}
	// Flip the control digit to anything else.
	wrong := good[:12] + string('0'+byte((good[12]-'0'+1)%10))
	if ValidateCNP(wrong) {
		t.Errorf("expected %q to fail control check", wrong)
	}
}

// computeControlDigit is the test-side mirror of the algorithm inside
// ValidateCNP. Kept in the test file so any bug in the production
// implementation can't accidentally mask itself.
func computeControlDigit(twelve string) int {
	if len(twelve) != 12 {
		return -1
	}
	sum := 0
	for i := 0; i < 12; i++ {
		sum += int(twelve[i]-'0') * CNPControlConstants[i]
	}
	c := sum % 11
	if c == 10 {
		c = 1
	}
	return c
}
